Repository openlattice/openlattice, pull requests merged in 2020-12, with the labels that each got.

#70 implement getUsers in LocalUserDirectoryService
  conductor-client/src/main/kotlin/com/openlattice/directory/LocalUserDirectoryService.kt
Labels: rolling deploy

#60 handle and skip columns with unknown datatypes when syncing external …
  conductor-client/src/main/kotlin/com/openlattice/organizations/ExternalDatabaseManagementService.kt
  indexer/src/main/kotlin/com/openlattice/BackgroundExternalDatabaseSyncingService.kt
Labels: rolling deploy

#68 add more documentation on permission updates
  api/src/main/java/com/openlattice/authorization/PermissionsApi.java
Labels: rolling deploy

#69 load and process expiring ids in batches of 10k
  conductor-client/src/main/kotlin/com/openlattice/data/storage/PostgresEntityDataQueryService.kt
  indexer/src/main/kotlin/com/openlattice/indexing/BackgroundExpiredDataDeletionService.kt
Labels: rolling deploy

#58 move logic to initialize org db out of entry processor to avoid cross…
  conductor-client/src/main/kotlin/com/openlattice/assembler/Assembler.kt
  conductor-client/src/main/kotlin/com/openlattice/assembler/processors/InitializeOrganizationAssemblyProcessor.kt
  conductor-client/src/main/kotlin/com/openlattice/hazelcast/serializers/InitializeOrganizationAssemblyProcessorStreamSerializer.kt
Labels: conductor

#47 put stuff in place to make a filtered request to load pages of data
  api/src/main/java/com/openlattice/data/DataApi.java
  api/src/main/kotlin/com/openlattice/data/FilteredDataPageDefinition.kt
  conductor-client/src/main/kotlin/com/openlattice/data/DataGraphManager.kt
  conductor-client/src/main/kotlin/com/openlattice/data/DataGraphService.kt
  conductor-client/src/main/kotlin/com/openlattice/data/storage/EntityDatastore.kt
  conductor-client/src/main/kotlin/com/openlattice/data/storage/PostgresDataQueries.kt
  conductor-client/src/main/kotlin/com/openlattice/data/storage/PostgresEntityDataQueryService.kt
  conductor-client/src/main/kotlin/com/openlattice/data/storage/PostgresEntityDatastore.kt
  conductor-client/src/test/kotlin/com/openlattice/data/MaterializedEntitySetViewTest.kt
  conductor-client/src/test/kotlin/com/openlattice/data/PostgresEntityDataQueryServiceTest.kt
  conductor-client/src/test/kotlin/com/openlattice/data/PostgresLinkedEntityDataQueryServiceTest.kt
  datastore/src/main/java/com/openlattice/datastore/data/controllers/DataController.java
Labels: conductor, datastore, restart deploy
